export interface Theme {
  name: string;
  properties: {
    [key: string]: string;
  };
}

export const blenderDark: Theme = {
  name: 'dark',
  properties: {
    '--bui-primary': '#4772b3',
    '--bui-bg-light': '#e0e0e0',
    '--bui-bg-dark': '#1d1d1d',
    '--bui-panel-bg': '#2b2b2b',
    '--bui-panel-header': '#303030',
    '--bui-input-bg': '#181818',
    '--bui-input-active-green': '#55802b',
    '--bui-input-active-yellow': '#8c7f21',
    '--bui-input-text': '#dedede',
    '--bui-tab-bg': '#222222',
    '--bui-tab-active': '#3d3d3d',
    '--bui-border-dark': '#3d3d3d',
    '--bui-text-color': '#cccccc',
    '--bui-border-radius': '4px',
    '--bui-highlight': '#5680c2',
    '--bui-surface-dark': '#303030',
    '--bui-surface-light': '#f5f5f5',
    '--bui-card-bg': '#303030',
    '--bui-menu-bg': '#2b2b2b',
    '--bui-menu-hover': '#4772b3',
    '--bui-menu-text-muted': '#8f8f8f',
    '--bui-menu-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.5), 0 2px 4px -1px rgba(0, 0, 0, 0.3)',
    '--bui-folder-icon': '#dcb67a',
    '--bui-channel-red': '#e04e4e',
    '--bui-channel-green': '#7ec928',
    '--bui-channel-blue': '#4e8ce0',
    '--bui-channel-yellow': '#d9bc26',
    '--bui-grid-line': '#2a2a2a',
    '--bui-grid-line-strong': '#353535',
    '--bui-text-muted': '#9ca3af',
  },
};

export const blenderLight: Theme = {
  name: 'light',
  properties: {
    '--bui-primary': '#4772b3',
    '--bui-bg-light': '#e0e0e0',
    '--bui-bg-dark': '#1d1d1d',
    '--bui-panel-bg': '#f0f0f0',
    '--bui-panel-header': '#f5f5f5',
    '--bui-input-bg': '#ffffff',
    '--bui-input-active-green': '#7bc654',
    '--bui-input-active-yellow': '#d4c24a',
    '--bui-input-text': '#333333',
    '--bui-tab-bg': '#d9d9d9',
    '--bui-tab-active': '#e6e6e6',
    '--bui-border-dark': '#d1d1d1',
    '--bui-text-color': '#222222',
    '--bui-border-radius': '4px',
    '--bui-highlight': '#375e97',
    '--bui-surface-dark': '#303030',
    '--bui-surface-light': '#f5f5f5',
    '--bui-card-bg': '#ffffff',
    '--bui-menu-bg': '#f0f0f0',
    '--bui-menu-hover': '#4772b3',
    '--bui-menu-text-muted': '#8f8f8f',
    '--bui-menu-shadow': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    '--bui-folder-icon': '#dcb67a',
    '--bui-channel-red': '#e04e4e',
    '--bui-channel-green': '#7ec928',
    '--bui-channel-blue': '#4e8ce0',
    '--bui-channel-yellow': '#d9bc26',
    '--bui-grid-line': '#d1d1d1',
    '--bui-grid-line-strong': '#b0b0b0',
    '--bui-text-muted': '#666666',
  },
};
