import { BuiThemeTokens } from './types';

export const createThemeProperties = (tokens: BuiThemeTokens): Record<string, string> => ({
  '--bui-color-primary': tokens.color.primary,
  '--bui-color-highlight': tokens.color.highlight,
  '--bui-color-text': tokens.color.text,
  '--bui-color-text-muted': tokens.color.textMuted,
  '--bui-color-text-disabled': tokens.color.textDisabled,
  '--bui-color-info': tokens.color.info,
  '--bui-color-success': tokens.color.success,
  '--bui-color-warning': tokens.color.warning,
  '--bui-color-danger': tokens.color.danger,

  '--bui-surface-app': tokens.surface.app,
  '--bui-surface-panel': tokens.surface.panel,
  '--bui-surface-panel-header': tokens.surface.panelHeader,
  '--bui-surface-panel-header-hover': tokens.surface.panelHeaderHover,
  '--bui-surface-panel-header-expanded': tokens.surface.panelHeaderExpanded,
  '--bui-surface-input': tokens.surface.input,
  '--bui-surface-input-gradient': tokens.surface.input,
  '--bui-surface-tab': tokens.surface.tab,
  '--bui-surface-tab-active': tokens.surface.tabActive,
  '--bui-surface-menu': tokens.surface.menu,
  '--bui-surface-card': tokens.surface.card,
  '--bui-surface-overlay': tokens.surface.overlay,

  '--bui-border-subtle': tokens.border.subtle,
  '--bui-border-default': tokens.border.default,
  '--bui-border-strong': tokens.border.strong,
  '--bui-border-hover': tokens.border.hover,
  '--bui-border-focus': tokens.border.focus,

  '--bui-spacing-xs': tokens.spacing.xs,
  '--bui-spacing-sm': tokens.spacing.sm,
  '--bui-spacing-md': tokens.spacing.md,
  '--bui-spacing-lg': tokens.spacing.lg,
  '--bui-spacing-row': tokens.spacing.row,

  '--bui-radius-sm': tokens.radius.sm,
  '--bui-radius-md': tokens.radius.md,
  '--bui-radius-lg': tokens.radius.lg,

  '--bui-font-family': tokens.typography.family,
  '--bui-font-size-xs': tokens.typography.sizeXs,
  '--bui-font-size-sm': tokens.typography.sizeSm,
  '--bui-font-size-md': tokens.typography.sizeMd,
  '--bui-font-weight-regular': tokens.typography.weightRegular,
  '--bui-font-weight-medium': tokens.typography.weightMedium,
  '--bui-font-weight-bold': tokens.typography.weightBold,

  '--bui-icon-size-sm': tokens.icon.sm,
  '--bui-icon-size-md': tokens.icon.md,
  '--bui-icon-size-lg': tokens.icon.lg,

  '--bui-density-compact-row': tokens.density.compactRow,
  '--bui-density-comfortable-row': tokens.density.comfortableRow,
  '--bui-control-height-sm': tokens.density.controlHeightSm,
  '--bui-control-height-md': tokens.density.controlHeightMd,

  '--bui-focus-outline-width': tokens.focus.outlineWidth,
  '--bui-focus-outline-offset': tokens.focus.outlineOffset,

  '--bui-motion-fast': tokens.motion.fast,
  '--bui-motion-normal': tokens.motion.normal,

  '--bui-channel-red': tokens.channel.red,
  '--bui-channel-green': tokens.channel.green,
  '--bui-channel-blue': tokens.channel.blue,
  '--bui-channel-yellow': tokens.channel.yellow,
  '--bui-folder-icon': tokens.asset.folder,

  // Legacy aliases kept for compatibility with existing component styles.
  '--bui-primary': tokens.color.primary,
  '--bui-highlight': tokens.color.highlight,
  '--bui-text-color': tokens.color.text,
  '--bui-text-muted': tokens.color.textMuted,
  '--bui-text-primary': tokens.color.text,
  '--bui-text-secondary': tokens.color.textMuted,
  '--bui-text-disabled': tokens.color.textDisabled,
  '--bui-bg-dark': tokens.surface.app,
  '--bui-bg-light': tokens.surface.overlay,
  '--bui-panel-bg': tokens.surface.panel,
  '--bui-panel-header': tokens.surface.panelHeader,
  '--bui-panel-header-hover': tokens.surface.panelHeaderHover,
  '--bui-panel-header-expanded': tokens.surface.panelHeaderExpanded,
  '--bui-input-bg': tokens.surface.input,
  '--bui-input-bg-gradient': tokens.surface.input,
  '--bui-tab-bg': tokens.surface.tab,
  '--bui-tab-active': tokens.surface.tabActive,
  '--bui-card-bg': tokens.surface.card,
  '--bui-menu-bg': tokens.surface.menu,
  '--bui-border-dark': tokens.border.default,
  '--bui-border-light': tokens.border.subtle,
  '--bui-input-border-hover': tokens.border.hover,
  '--bui-border-radius': tokens.radius.md,
  '--bui-radius-sm-legacy': tokens.radius.sm,
  '--bui-font-display': tokens.typography.family,
  '--bui-font-size-small': tokens.typography.sizeSm,
  '--bui-accent-blue': tokens.color.primary,
  '--bui-accent-blue-hover': tokens.color.highlight,
});

